### ISSUE TITLE
Missing proxy endpoint 'process-status'

### ISSUE THREAD

**Issue by EtienneWallet** [gfusee/xnetwork#16]
# What happened

I am running xnetwork with the following config:

```json
{
    "shouldHaveElasticSearch": true,
    "shouldHaveMySQL": true,
    "shouldHaveRedis": true,
    "shouldHaveRabbitMQ": true,
    "shouldHaveApi": true,
    "numberOfShards": 2,
    "mxOpsScenesPath": "<my_scene>",
    "initialEGLDAddress": "<my_address>"
}
```

This code produces an error 404:

```python
from multiversx_sdk_network_providers import ProxyNetworkProvider
proxy = ProxyNetworkProvider("http://localhost:7950")
tx_hash = "<my_tx_hash>"
on_chain_tx = proxy.get_transaction(tx_hash, True)
```
```bash
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mxops_env/lib/python3.8/site-packages/multiversx_sdk_network_providers/proxy_network_provider.py", line 192, in do_get
    response.raise_for_status()
  File "/home/user/anaconda3/envs/mxops_env/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:7950/transaction/deb7924e4a6d26a0a6c712638014cbd189120b42743b8e4a58288bbbf92e69fb/process-status
```

# Expected Results and Guess

I expect this code to return the on chain transaction **with** the completion state. My guess is that xnetwork is not up-to-date with the latest proxy version.

# Info
python v3.8.18
Node v18.18.0
npm v9.8.1

## Python Env Requirements Used
multiversx-sdk-cli~=8.1.2
multiversx_sdk_core~=0.6.0
multiversx_sdk_network_providers~=0.11.0
multiversx-sdk-wallet~=0.7.0

**Comment by gfusee** [comment]
Solved in v0.2.0. More details here: https://github.com/gfusee/xnetwork/releases/tag/v0.2.0
